package com.mycompany.sistemaprestamosbeta;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;

public class VistaEncargado extends javax.swing.JFrame {

    private VistaInicioSesion vistaGeneral;
    private ArrayList<Prestamo> prestamosPendientes;
    private BaseDeDatosUsuarios baseDeDatos;
    private int indice;
    
    public VistaEncargado() {
        initComponents();
        prestamosPendientes = new ArrayList<>();
        baseDeDatos = new BaseDeDatosUsuarios();
        indice = 0;
    }

    public void obtenerBaseDeDatos(BaseDeDatosUsuarios bd){
        baseDeDatos = bd;
    }
    
    public void obtenerInicioDeSesion(VistaInicioSesion vista){
        vistaGeneral = new VistaInicioSesion();
        vistaGeneral = vista;
    }
    
    public void recibirDatosUsuario(int codigo, String nombre, String apellidos, String correo, ArrayList materialesSolicitados){
        Calendar date = Calendar.getInstance();
        date.setTime(new Date());
        String fecha = String.valueOf(date.get(Calendar.YEAR)) + "/" + String.valueOf(date.get(Calendar.MONTH)) + "/" + String.valueOf(date.get(Calendar.DAY_OF_MONTH)) ;
        String hora = String.valueOf(date.get(Calendar.HOUR) + ":" + String.valueOf(date.get(Calendar.MINUTE)));
        Prestamo p = new Prestamo(codigo, nombre, apellidos, correo, fecha , hora , materialesSolicitados);
        //textoMatricula.setText("Matricula/Codigo del solicitante: " + codigo);
        //textoNombre.setText("Nombre del solicitante: " + nombre);
        //textoApellidos.setText("Apellidos del solicitante: " +apellidos);
        //textoCorreo.setText("Correo del solicitante: " +correo);
        String solicitante = String.valueOf(codigo) + " " +nombre+ " " +apellidos;
        prestamosRealizados.addItem(solicitante);
        prestamosPendientes.add(p);
    }
    
    public void recibirMensaje(String mensaje){
        textoNombre.setText(mensaje);
    }
    
    public void regresarAlInicio(){
        vistaGeneral.setVisible(true);
        vistaGeneral.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoNombre = new javax.swing.JLabel();
        botonParaRegresar = new javax.swing.JButton();
        textoMatricula = new javax.swing.JLabel();
        textoFecha = new javax.swing.JLabel();
        textoHora = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JLabel();
        prestamosRealizados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoMaterialesSolicitados = new javax.swing.JTextArea();
        botonVerPrestamo = new javax.swing.JButton();
        comboBoxMaterialesPedidos = new javax.swing.JComboBox<>();
        botonParaRechazarMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoNombre.setText("Nombre del solicitante:");

        botonParaRegresar.setText("Volver a iniciar sesion");
        botonParaRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParaRegresarActionPerformed(evt);
            }
        });

        textoMatricula.setText("Matricula/Codigo del solicitante:");

        textoFecha.setText("Fecha de solicitud:");

        textoHora.setText("Hora de solicitud:");

        textoApellidos.setText("Apellidos del solicitante: ");

        textoCorreo.setText("Correo del solicitante: ");

        prestamosRealizados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                prestamosRealizadosItemStateChanged(evt);
            }
        });

        textoMaterialesSolicitados.setColumns(20);
        textoMaterialesSolicitados.setRows(5);
        jScrollPane1.setViewportView(textoMaterialesSolicitados);

        botonVerPrestamo.setText("Ver prestamo escodigo");
        botonVerPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPrestamoActionPerformed(evt);
            }
        });

        botonParaRechazarMaterial.setText("Rechazar material");
        botonParaRechazarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParaRechazarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textoHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(botonParaRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prestamosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMaterialesPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonParaRechazarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prestamosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonParaRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxMaterialesPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonParaRechazarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonParaRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParaRegresarActionPerformed
        regresarAlInicio();
    }//GEN-LAST:event_botonParaRegresarActionPerformed

    private void prestamosRealizadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_prestamosRealizadosItemStateChanged
        
    }//GEN-LAST:event_prestamosRealizadosItemStateChanged

    private void botonVerPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPrestamoActionPerformed
        indice = prestamosRealizados.getSelectedIndex();
        System.out.println("El indice del item es " + indice);
        if(indice>-1){
            Prestamo prestamoAuxiliar = prestamosPendientes.get(indice);
            textoMatricula.setText("Matricula/Codigo del solicitante: " + prestamoAuxiliar.getCodigoSolicitante());
            textoNombre.setText("Nombre del solicitante: " + prestamoAuxiliar.getNombreSolicitante());
            textoApellidos.setText("Apellidos del solicitante: " +prestamoAuxiliar.getApellidoSolicitante());
            textoCorreo.setText("Correo del solicitante: " +prestamoAuxiliar.getCorreoSolicitante());
            textoFecha.setText("Fecha de solicitud: " +prestamoAuxiliar.getFechaCreacion());
            textoHora.setText("Hora de solicitud: " +prestamoAuxiliar.getHoraCreacion());
            textoMaterialesSolicitados.setText("");
            ArrayList<Material> materialesASolicitar = new ArrayList();
            materialesASolicitar = prestamoAuxiliar.getMaterialesSolicitados();
            for(int i=0; i<materialesASolicitar.size(); i++){
                Material materialAAgregar = materialesASolicitar.get(i);
                String nombreDelMaterial = materialAAgregar.getNombre();
                String descripcionDelMaterial = materialAAgregar.getDescripcion();
                String potenciadorDelMaterial = materialAAgregar.getPotenciadorEscogido();
                String mantenibleDelMaterial = String.valueOf(materialAAgregar.isMantenible());
                String textoAAgregar = nombreDelMaterial + " " + descripcionDelMaterial + " " + potenciadorDelMaterial + " " + mantenibleDelMaterial;
                textoMaterialesSolicitados.append(textoAAgregar+"\n");
                comboBoxMaterialesPedidos.addItem(textoAAgregar);
            }
        }
    }//GEN-LAST:event_botonVerPrestamoActionPerformed

    private void botonParaRechazarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParaRechazarMaterialActionPerformed
        int indicePrestamos = prestamosRealizados.getSelectedIndex();
        int index = comboBoxMaterialesPedidos.getSelectedIndex();
        if(index>-1 && indicePrestamos>-1){
            Prestamo prestamoAuxiliar = prestamosPendientes.get(indicePrestamos);
            ArrayList<Material> materialesASolicitar = new ArrayList();
            materialesASolicitar = prestamoAuxiliar.getMaterialesSolicitados();
            materialesASolicitar.remove(index);
            prestamosPendientes.get(indicePrestamos).setMaterialesSolicitados(materialesASolicitar);
            textoMaterialesSolicitados.setText("");
            comboBoxMaterialesPedidos.removeAllItems();
            for(int i=0; i<materialesASolicitar.size(); i++){
                Material materialAAgregar = materialesASolicitar.get(i);
                String nombreDelMaterial = materialAAgregar.getNombre();
                String descripcionDelMaterial = materialAAgregar.getDescripcion();
                String potenciadorDelMaterial = materialAAgregar.getPotenciadorEscogido();
                String mantenibleDelMaterial = String.valueOf(materialAAgregar.isMantenible());
                String textoAAgregar = nombreDelMaterial + " " + descripcionDelMaterial + " " + potenciadorDelMaterial + " " + mantenibleDelMaterial;
                textoMaterialesSolicitados.append(textoAAgregar+"\n");
                comboBoxMaterialesPedidos.addItem(textoAAgregar);
            }
        }
        if(comboBoxMaterialesPedidos.getItemCount()==0){
            prestamosRealizados.removeItemAt(indicePrestamos);
            textoMaterialesSolicitados.setText("");
            textoMatricula.setText("Matricula/Codigo del solicitante: ");
            textoNombre.setText("Nombre del solicitante: ");
            textoApellidos.setText("Apellidos del solicitante: ");
            textoCorreo.setText("Correo del solicitante: ");
            textoFecha.setText("Fecha de solicitud: ");
            textoHora.setText("Hora de solicitud: ");
        }
    }//GEN-LAST:event_botonParaRechazarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEncargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonParaRechazarMaterial;
    private javax.swing.JButton botonParaRegresar;
    private javax.swing.JButton botonVerPrestamo;
    private javax.swing.JComboBox<String> comboBoxMaterialesPedidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> prestamosRealizados;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoCorreo;
    private javax.swing.JLabel textoFecha;
    private javax.swing.JLabel textoHora;
    private javax.swing.JTextArea textoMaterialesSolicitados;
    private javax.swing.JLabel textoMatricula;
    private javax.swing.JLabel textoNombre;
    // End of variables declaration//GEN-END:variables
}
