/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaprestamosbeta;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author joaha
 */
public class VistaInicioSesion extends javax.swing.JFrame {

    private BaseDeDatosUsuarios baseDeDatos;
    private VistaAlumnoMaestro vistaUsuario;
    private VistaEncargado vistaEncargado;
    
    public VistaInicioSesion() {
        initComponents();
        baseDeDatos = new BaseDeDatosUsuarios();
        vistaEncargado = new VistaEncargado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        espacioDeCorreo = new javax.swing.JTextField();
        botonDeInicio = new javax.swing.JButton();
        espacioDePassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        espacioDeCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioDeCorreoActionPerformed(evt);
            }
        });

        botonDeInicio.setText("Iniciar sesión");
        botonDeInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeInicioActionPerformed(evt);
            }
        });

        espacioDePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioDePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(espacioDePassword)
                    .addComponent(botonDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacioDeCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(espacioDeCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(espacioDePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espacioDeCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioDeCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacioDeCorreoActionPerformed

    private void espacioDePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioDePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacioDePasswordActionPerformed

    private void botonDeInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeInicioActionPerformed
        vistaUsuario = new VistaAlumnoMaestro();
        ArrayList<Alumno> auxiliar1 = baseDeDatos.getAlumnos();
        ArrayList<Maestro> auxiliar2 = baseDeDatos.getMaestros();
        ArrayList<Encargado> auxiliar3 = baseDeDatos.getEncargadosDeLaboratorio();
        String correoEscrito = espacioDeCorreo.getText();
        String passwordEscrita = espacioDePassword.getText();
        int tipoDeUsuario = 0;
        String passwordCorrecta = "";
        Alumno alumnoSolicitante = new Alumno();
        Maestro maestroSolicitante = new Maestro();
        Encargado encargadoSolicitante = new Encargado();
        int numeroAlumnoAuxiliar = 0;
        int numeroMaestroAuxiliar = 0;
        int numeroEncargadoAuxiliar = 0;
        
        if(!correoEscrito.equals("") && !passwordEscrita.equals("")){
        for(int i=0; i<auxiliar1.size(); i++){
            if(auxiliar1.get(i).getCorreo().equals(correoEscrito)){
                tipoDeUsuario = 1;
                passwordCorrecta = auxiliar1.get(i).getContraseña();
                numeroAlumnoAuxiliar = i;
            }
        }
        for(int j=0; j<auxiliar2.size(); j++){
            if(auxiliar2.get(j).getCorreo().equals(correoEscrito)){
                tipoDeUsuario = 2;
                passwordCorrecta = auxiliar2.get(j).getContraseña();
                numeroMaestroAuxiliar = j;
            }
        }
        for(int k=0; k<auxiliar3.size(); k++){
            if(auxiliar3.get(k).getCorreo().equals(correoEscrito)){
                tipoDeUsuario = 3;                
                passwordCorrecta = auxiliar3.get(k).getContraseña();
                numeroEncargadoAuxiliar = k;
            }
        }
        if(passwordCorrecta.equals(passwordEscrita)){
            if(tipoDeUsuario == 1){
                alumnoSolicitante = auxiliar1.get(numeroAlumnoAuxiliar);
                vistaUsuario.obtenerAlumno(alumnoSolicitante, 1);
                vistaUsuario.obtenerInicioDeSesion(this);
                vistaUsuario.setVisible(true);
                setVisible(false);
                vistaUsuario.obtenerVistaEncargado(vistaEncargado);
                vistaUsuario.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            }
            else if(tipoDeUsuario == 2){
                maestroSolicitante = auxiliar2.get(numeroMaestroAuxiliar);
                vistaUsuario.obtenerMaestro(maestroSolicitante, 2);    
                vistaUsuario.obtenerInicioDeSesion(this);
                vistaUsuario.setVisible(true);
                setVisible(false);
                vistaUsuario.obtenerVistaEncargado(vistaEncargado);
                vistaUsuario.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            }
            else if(tipoDeUsuario == 3){
            encargadoSolicitante = auxiliar3.get(numeroEncargadoAuxiliar);
            vistaEncargado = new VistaEncargado();
            vistaEncargado.setVisible(true);
            vistaEncargado.obtenerInicioDeSesion(this);
            vistaEncargado.setTitle("Vista encargado");
            }
        }
        else{
            System.out.println("Usuario no valido");
        }
        
        }
    }//GEN-LAST:event_botonDeInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDeInicio;
    private javax.swing.JTextField espacioDeCorreo;
    private javax.swing.JTextField espacioDePassword;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
