package com.mycompany.sistemaprestamosbeta;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;

public class VistaAlumnoMaestro extends javax.swing.JFrame {

    private ArrayList listaPotenciadores;
    private ArrayList<Material> listaMateriales;
    private ArrayList<Material> listaDeMaterialesParaPedir;
    private Maestro maestro;
    private Alumno alumno;
    private VistaInicioSesion vistaGeneral;
    private VistaEncargado vistaEncargado;
    private int tipoDeUsuarioActual;
    
    public VistaAlumnoMaestro(){
        initComponents();
        listaPotenciadores = new ArrayList();
        listaMateriales = new ArrayList<>();
        listaDeMaterialesParaPedir = new ArrayList<>();
        llenarPotenciadores();
        llenarListaDeMateriales();
        actualizarListaMateriales();
        maestro = new Maestro();
        alumno = new Alumno();
        vistaGeneral = new VistaInicioSesion();
        vistaEncargado = new VistaEncargado();
        tipoDeUsuarioActual = 0;
    }
    
    public void obtenerInicioDeSesion(VistaInicioSesion vista){
        vistaGeneral = vista;
    }
    
    public void obtenerVistaEncargado(VistaEncargado vista){
        vistaEncargado = vista;
    }
    
    public void regresarAlInicio(){
        setVisible(false);
        vistaGeneral.setVisible(true);
        vistaGeneral.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    public void obtenerAlumno(Alumno a, int valor){
        alumno = a;
        tipoDeUsuarioActual = valor;
        matriculaDelUsuario.setText(String.valueOf(alumno.getMatricula()));
        String nombre = alumno.getNombre();
        String apellidos = alumno.getApellidos();
        nombreDelUsuario.setText(nombre + " " + apellidos);
        setTitle("Vista para alumnos");
    }
    
    public void obtenerMaestro(Maestro m, int valor){
        maestro = m;
        tipoDeUsuarioActual = valor;
        matriculaDelUsuario.setText(String.valueOf(maestro.getCodigoMaestro()));
        String nombre = maestro.getNombre();
        String apellidos = maestro.getApellidos();
        nombreDelUsuario.setText(nombre + " " + apellidos);
        setTitle("Vista para maestros");
    }

    public void actualizarListaMateriales(){
        for(int i = 0; i<listaMateriales.size(); i++){
            String nombreDelMaterial = listaMateriales.get(i).getNombre();
            nombreDeLosMateriales.addItem(nombreDelMaterial);            
        }
    }
    
    public void llenarPotenciadores(){
        listaPotenciadores.add("N/A");
        listaPotenciadores.add("mili");
        listaPotenciadores.add("micro");
        listaPotenciadores.add("nano");
        listaPotenciadores.add("pico");
        listaPotenciadores.add("kilo");
    }
    
    public void llenarListaDeMateriales(){
      String nombre = "C:\\Users\\joaha\\OneDrive\\Documentos\\NetBeansProjects\\SistemaPrestamosBeta\\src\\main\\java\\com\\mycompany\\sistemaprestamosbeta\\Materiales del laboratorio.csv";
      File archivo = null;
      FileReader fr = null;
      BufferedReader br = null;
      int contador = 0;
      String line = "";  
      String splitBy = ",";
    try{  
    //parsing a CSV file into BufferedReader class constructor  
    br = new BufferedReader(new FileReader(nombre));  
    while ((line = br.readLine()) != null){   //returns a Boolean value    
        //System.out.println(line);    // use comma as separator
        if(contador>0){
            //System.out.println(line);
            String[] datos = line.split(splitBy);
            String nombreMaterial = datos[0];
            boolean mantenible = false;
            boolean potenciable = false;
            if(datos[1].equals("TRUE")){
                mantenible = true;
            }
            if(datos[2].equals("TRUE")){
                potenciable = true;
            }
            Material nuevoMaterial = new Material(nombreMaterial, mantenible, potenciable);
            listaMateriales.add(nuevoMaterial);
        }
        contador++;
    }  
    }catch(IOException e){  
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreDeLosMateriales = new javax.swing.JComboBox<>();
        textoNombreMaterial = new javax.swing.JLabel();
        textoDescripcionMaterial = new javax.swing.JLabel();
        descripcionDeLosMateriales = new javax.swing.JTextField();
        textoCantidadMaterial = new javax.swing.JLabel();
        textPotenciadores = new javax.swing.JLabel();
        potenciadorDelMaterial = new javax.swing.JComboBox<>();
        botonParaAgregarMaterial = new javax.swing.JButton();
        cantidadDeMaterial = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        materialesASolicitar = new javax.swing.JTextArea();
        matriculaDelUsuario = new javax.swing.JLabel();
        nombreDelUsuario = new javax.swing.JLabel();
        botonInicioSesion = new javax.swing.JButton();
        botonPrueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreDeLosMateriales.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nombreDeLosMaterialesItemStateChanged(evt);
            }
        });
        nombreDeLosMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDeLosMaterialesActionPerformed(evt);
            }
        });

        textoNombreMaterial.setText("Nombre del material");

        textoDescripcionMaterial.setText("Descripción");

        descripcionDeLosMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionDeLosMaterialesActionPerformed(evt);
            }
        });

        textoCantidadMaterial.setText("Cantidad");

        textPotenciadores.setText("Potenciador");

        potenciadorDelMaterial.setEnabled(false);

        botonParaAgregarMaterial.setText("Agregar material");
        botonParaAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParaAgregarMaterialActionPerformed(evt);
            }
        });

        cantidadDeMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        materialesASolicitar.setColumns(20);
        materialesASolicitar.setRows(5);
        jScrollPane2.setViewportView(materialesASolicitar);

        botonInicioSesion.setText("Volver a iniciar sesion");
        botonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioSesionActionPerformed(evt);
            }
        });

        botonPrueba.setText("Mandar mensaje");
        botonPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(matriculaDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombreDelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonParaAgregarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPotenciadores, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCantidadMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoNombreMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addComponent(textoDescripcionMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potenciadorDelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcionDeLosMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreDeLosMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonInicioSesion)
                        .addGap(26, 26, 26)
                        .addComponent(botonPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matriculaDelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreDelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(textoNombreMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombreDeLosMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoDescripcionMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descripcionDeLosMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoCantidadMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textPotenciadores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(potenciadorDelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonParaAgregarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(botonInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionDeLosMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionDeLosMaterialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionDeLosMaterialesActionPerformed

    private void nombreDeLosMaterialesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nombreDeLosMaterialesItemStateChanged
        String nombreMaterial = nombreDeLosMateriales.getSelectedItem().toString();
        Material materialEscogido = new Material();
        for(int j=0; j<listaMateriales.size(); j++){
            if((listaMateriales.get(j).getNombre().equals(nombreMaterial))){
                materialEscogido = listaMateriales.get(j);
            }
        }
        if(materialEscogido.isUsaPotenciadores()){
            potenciadorDelMaterial.setEnabled(true);
            for(int i=0; i<listaPotenciadores.size(); i++){
                potenciadorDelMaterial.addItem(listaPotenciadores.get(i).toString());
            }
        }
        else{
            potenciadorDelMaterial.setEnabled(false);
        }
    }//GEN-LAST:event_nombreDeLosMaterialesItemStateChanged

    private void nombreDeLosMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDeLosMaterialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDeLosMaterialesActionPerformed

    private void botonParaAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParaAgregarMaterialActionPerformed
        String nombreDelMaterial = nombreDeLosMateriales.getSelectedItem().toString();
        String descripcionDelMaterial = "";
        if(descripcionDeLosMateriales.equals("")){
            descripcionDelMaterial = "";
        }
        else{
        descripcionDelMaterial = descripcionDeLosMateriales.getText();            
        }      
        int cantidadDeMateriales = Integer.parseInt(cantidadDeMaterial.getSelectedItem().toString());
        String potDelMaterial = "";
        boolean esMantenible = false;
        if(potenciadorDelMaterial.isEnabled()){
            potDelMaterial = potenciadorDelMaterial.getSelectedItem().toString();
        }
        else{
            potDelMaterial = "N/A";
        }
        for(int i = 0; i<listaMateriales.size(); i++){
            if(listaMateriales.get(i).getNombre().equals(nombreDelMaterial)){
               esMantenible = listaMateriales.get(i).isMantenible();
            }
        }
        System.out.println(nombreDelMaterial);
        System.out.println(descripcionDelMaterial);
        System.out.println(cantidadDeMateriales);
        System.out.println(potDelMaterial);
        System.out.println(esMantenible);
        for(int j = 0; j<cantidadDeMateriales; j++){
        Material materialTemp = new Material(nombreDelMaterial, descripcionDelMaterial, potDelMaterial, esMantenible);
        listaDeMaterialesParaPedir.add(materialTemp);
        materialesASolicitar.append(materialTemp.toString()+"\n");
        }
    }//GEN-LAST:event_botonParaAgregarMaterialActionPerformed

    private void botonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioSesionActionPerformed
        regresarAlInicio();
    }//GEN-LAST:event_botonInicioSesionActionPerformed

    private void botonPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPruebaActionPerformed
        if(tipoDeUsuarioActual == 1){
            vistaEncargado.recibirDatosUsuario(alumno.getMatricula(), alumno.getNombre(), alumno.getApellidos(), alumno.getCorreo(), listaDeMaterialesParaPedir);
        }
        if(tipoDeUsuarioActual == 2){
            vistaEncargado.recibirDatosUsuario(maestro.getCodigoMaestro(), maestro.getNombre(), maestro.getApellidos(), maestro.getCorreo(), listaDeMaterialesParaPedir);
        }
        listaDeMaterialesParaPedir.clear();
        materialesASolicitar.setText("");
        //dispose();
    }//GEN-LAST:event_botonPruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlumnoMaestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlumnoMaestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicioSesion;
    private javax.swing.JButton botonParaAgregarMaterial;
    private javax.swing.JButton botonPrueba;
    private javax.swing.JComboBox<String> cantidadDeMaterial;
    private javax.swing.JTextField descripcionDeLosMateriales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea materialesASolicitar;
    private javax.swing.JLabel matriculaDelUsuario;
    private javax.swing.JComboBox<String> nombreDeLosMateriales;
    private javax.swing.JLabel nombreDelUsuario;
    private javax.swing.JComboBox<String> potenciadorDelMaterial;
    private javax.swing.JLabel textPotenciadores;
    private javax.swing.JLabel textoCantidadMaterial;
    private javax.swing.JLabel textoDescripcionMaterial;
    private javax.swing.JLabel textoNombreMaterial;
    // End of variables declaration//GEN-END:variables
}
